
version: '3'
services:
  user_service:
    build: 
      # context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE_DIR: user_service
        SERVICE_PORT: 8002
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    environment:
      - APITYPE=user_service
      - ENVPORT=8002
  customer_service:
    build: 
      # context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE_DIR: customer_service
        SERVICE_PORT: 8001
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    environment:
      - APITYPE=customer_service
      - ENVPORT=8001