
version: '3'
services:
  user_service:
    build: 
      # context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE_DIR: user_service
    ports:
      - "8002:4000"
  customer_service:
    build: 
      # context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE_DIR: customer_service
    ports:
      - "8001:4000"
